---
- hosts: all
  vars:
    - ansadm_password: '$6$tcUj/FyNqZb77q03$aPxJWUFsanGfSuNlZbKXhKEnSc/0m4R7DSGdaod4makt8cVn.8894fQkH5v526pDOH9wcGwR7gBvAGYOcU8JB1'
  gather_facts: no

  tasks:

  - name: 1. Add user ANSADM
    user:
         name=ansibleops
         password={{ ansadm_password }}
   
  - name: 2. Change Expire Password Account to never
    command: chage -E -1 ansibleops
          
  - name: 3. Add remote user to sudoers
    lineinfile:
         "dest=/etc/sudoers
         regexp='^remote ALL'
         line='ansibleops ALL=(ALL) NOPASSWD: ALL'
         state=present"
 
  - name: 4. install ssh key
    authorized_key: user=ansibleops 
                    key="{{ lookup('file', '/home/ansibleops/.ssh/id_rsa.pub') }}" 
                    state=present    
